corretto/corretto-8

src/jdk/src/windows/native/sun/windows/ShellFolder2.cpp

This is a backport of https://bugs.openjdk.java.net/browse/JDK-8213583
If a Windows Desktop shortcut is bad (the file to which it points is gone), regardless of the default directory set in JFilechooser, an error is thrown saying that the shortcut is bad even though JFilechooser was not instructed to look at the Desktop.
The following PullRequests correspond to fixes that are in the same BPR:
#71
#73
Java SE 8u202 b32 BPR includes three backports from OpenJDK12. This is one of them.
Original patch:
https://hg.openjdk.java.net/jdk/jdk12/rev/c8071863df80
The patch was applied without issues

Back port from OpenJDK 12, fixing JDK-8213583: Error while opening the JFileChooser when desktop contains shortcuts pointing to deleted files.

---

src/jdk/src/windows/classes/sun/awt/windows/WToolkit.java
src/jdk/src/windows/classes/sun/awt/windows/WWindowPeer.java
src/jdk/test/java/awt/Toolkit/DisplayChangesException/DisplayChangesException.java

This is a backport of https://bugs.openjdk.java.net/browse/JDK-8207070
Issue with webstart app where the popup menu appear on a wrong screen
on an initial one-screen setup and it changes to multi-monitor.
The popup is displayed on wrong screen.
The issue does not happen with this same application when it is launched
locally (not via webstart).
The following PullRequests correspond to fixes that are in the same BPR:
https://github.com/corretto/corretto-8/pull/70
https://github.com/corretto/corretto-8/pull/73
Java SE 8u202 b32 BPR includes three backports from OpenJDK12. This is one of them.
Original patch:
https://hg.openjdk.java.net/jdk/jdk12/rev/6cf31480d3a3
Patch had to be split into multiple smaller files before applying due to relative file locations change.
Changes on file …

Back port from OpenJDK 12, fixing JDK-8207070: Webstart app popup on wrong screen in a one-screen setup changing to multi-monitor.

---

src/hotspot/src/os/aix/vm/os_aix.cpp
src/hotspot/src/os/bsd/vm/os_bsd.cpp
src/hotspot/src/os/linux/vm/os_linux.cpp
src/hotspot/src/os/solaris/vm/os_solaris.cpp
src/hotspot/src/os/windows/vm/os_windows.cpp
src/hotspot/src/share/vm/runtime/os.hpp
src/hotspot/src/share/vm/utilities/vmError.cpp

This is a backport of https://bugs.openjdk.java.net/browse/JDK-8027434
When calling fork/exec the process is duplicated by fork and only then the new copy is replaced using exec. That leads to problems when the JVM uses most of the memory and only a small program is to be started. 
The problem was solved for Process.start in 2009, but was apparently not solved for execution of the "-XX:OnOutOfMemoryError" handler. 
-XX:OnOutOfMemoryError=reboot did not work, even though the log showed it would be started. Looking in the openJDK 7u40 sources, I found that this code still uses fork/exec instead of vfork, which was the solution for the Process.start case.... 
The following PullRequests correspond to fixes that are in the same BPR:
#70 
#71 
Java SE 8u202 b32 BPR includes three backports from …

Back port from OpenJDK 12, fixing JDK-8027434: "-XX:OnOutOfMemoryError" uses fork instead of vfork

---

src/jdk/src/windows/classes/sun/awt/windows/WToolkit.java

There is a missing declaration on WToolkit.java breaking windows builds.
https://github.com/corretto/corretto-8/pull/71/files

Add missing declaration to backport of JDK-8207070

---

installers/linux/universal/deb/build.gradle
installers/linux/universal/rpm/build.gradle

`/jre/lib/applet` directory is missing in Corretto8 generic Linux deb and rpm, which makes it inconsistent with generic Linux tgz and other artifacts. This patch adds it back to deb and rpm.

Include /jre/lib/applet directory in rpm and deb packaging

---

installers/linux/universal/deb/build.gradle
installers/linux/universal/deb/jinfo/jinfo.template
installers/linux/universal/test/docker/deb/run_test.sh

Include jinfo file in deb packaging to support 'update-java-alternatives' command.
When packaging deb package, inflate jinfo template and copy it to `/usr/lib/jvm/` directory. Make it possible to update Corretto alternatives through `update-java-alternatives` command.
Inflated jinfo file example:
```
name=java-1.8.0-amazon-corretto
alias=java-1.8.0-amazon-corretto
priority=10800202
section=main
jre java /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/java
jre jjs /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/jjs
jre keytool /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/keytool
jre orbd /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/orbd
jre pack200 /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/pack200
jre policytool /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/policytool
jre …
```

Add jinfo file to Debian package

---

src/jdk/src/share/classes/sun/java2d/pisces/PiscesCache.java
src/jdk/src/share/classes/sun/java2d/pisces/PiscesTileGenerator.java
src/jdk/test/sun/java2d/pisces/OpenJDKFillBug.java

In reference to issue: https://github.com/corretto/corretto-8/issues/93
Describe the bug
JDK-8048782 describes an issue where sun.java2d.pisces.PiscesCache constructor that accepts min/max x and y arguments - the internal 'bboxX1' and 'bboxY1' are set to values one greater than given maximum X and Y values. This effectively causes an "off by 1" error.
The fix has already been backported to OpenJDK9 and should also be brought back to OpenJDK8 as we've experienced this issue first hand.
References:
https://bugs.openjdk.java.net/browse/JDK-8048782
http://mail.openjdk.java.net/pipermail/2d-dev/2014-June/004652.html
To Reproduce
An sample application in the JBS issue is available, along with a JTREG test in the patch.
Expected behavior
The sample program and JTREG should pass.
Platform …

Backport JDK-8048782: OpenJDK: PiscesCache : xmax/ymax rounding up can cause RasterFormatException

---

src/hotspot/src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.hpp
src/hotspot/src/cpu/aarch64/vm/globals_aarch64.hpp
src/hotspot/src/cpu/aarch64/vm/macroAssembler_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/macroAssembler_aarch64.hpp
src/hotspot/src/cpu/aarch64/vm/methodHandles_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/sharedRuntime_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/templateInterpreter_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/templateTable_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/vm_version_aarch64.cpp
src/hotspot/src/os/linux/vm/os_linux.cpp
src/hotspot/src/os/linux/vm/os_linux.hpp
src/hotspot/src/share/vm/adlc/adlparse.cpp
src/hotspot/src/share/vm/adlc/dfa.cpp
src/hotspot/src/share/vm/adlc/formssel.cpp
src/hotspot/src/share/vm/c1/c1_LIRAssembler.cpp
src/hotspot/src/share/vm/memory/metaspace.cpp
src/hotspot/src/share/vm/runtime/vframeArray.cpp

Upgrade aarch64 port to Icedtea3.11.
Keep current with Icedtea aarch64 port.
Hotspot jtreg tests pass better than x64 port.
Works on OS: Amazon Linux 2 only
Applies to version Corretto-8.202.08.3
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Upgrade aarch64 port to Icedtea3.11.

---

installers/linux/universal/test/build.gradle
installers/linux/universal/test/docker/rpm-alternatives/Dockerfile
installers/linux/universal/test/docker/rpm-alternatives/run_test.sh

With this change, we can add additional tests by create a new directory
under 'Docker' that contains its own Dockerfile.
This is a refactoring to make it easier to write tests for #67.

Simplify adding tests for universal linux binaries.

---

installers/linux/universal/rpm/build.gradle
installers/linux/universal/test/docker/rpm-provide-java/Dockerfile
installers/linux/universal/test/docker/rpm-provide-java/run_test.sh

This fixes #67 by adding `java` and `java-headless` as provided by the generic RPM. In addition, there's a test showing that installing jetty will not bring in java-1.8.0-openjdk on AL2.

Provide 'java' to yum in the generic RPM.

---

installers/linux/universal/deb/build.gradle

Replace the hard-coded x86 arch tag and allow the build script to
recognize aarch64.
Arch designation reference: https://help.ubuntu.com/lts/installation-guide/arm64/ch02s01.html
Tested in a centOS-7-aarch64 docker instance:
```
...
total 95544
-rw-r--r-- 1 root root      842 May 23 23:42 java-1.8.0-amazon-corretto-jdk_8.212.04-2_arm64.changes
-rw-r--r-- 1 root root 97831710 May 23 23:42 java-1.8.0-amazon-corretto-jdk_8.212.04-2_arm64.deb
```

Add support for building deb package on aarch64

---

installers/linux/universal/rpm/build.gradle

redline-1.2.7 is not able to recognize aarch64 as a valid architecture,
causing the rpm gradle task fail silently on aarch64. The issue is fixed
in redline-1.2.8 but the package has not been released. This commit
bundles a redline-1.2.7 jar file with the fix backported from 1.2.8.
This allows us to unblock the build on aarch64.
Tested in a CentOS-7 aarch64 docker instance:
```
...
total 95520
-rw-r--r-- 1 root root 97811030 May 29 00:02 java-1.8.0-amazon-corretto-devel-1.8.0_202.b08-2.aarch64.rpm
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
```

Add support for building rpm package on aarch64

---

src/hotspot/src/os/linux/vm/os_linux.hpp

Diff/Patch has created two declarations of the same function on `src/hotspot/src/os/linux/vm/os_linux.hpp`. This breaks the build.
Corretto includes the IcedTea port of aarch64. However, some of the changes that were done for the port are also upstreamed into the openjdk repository. During a rebase, Diff/Patch failed to detect a conflict. That code breaks the build.

Fix bad rebase of aarch64 port on 8u212.

---

src/hotspot/src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/stubGenerator_aarch64.cpp

These 2 bugfixes fix intrinsic System.arraycopy on aarch64
JDK-1560
we run into problem for[ …

[aarch64] add JDK-8224671 and JDK-8219006

---

installers/mac/pkg/templates/introduction.html.template
installers/mac/tar/templates/Info.plist.template

The mac installer reads the CFBundleVersion key from `Info.plist` to determine if a component should be installed. Change the key to reflect the corretto version so the installer will not overwrite a new corretto version with an old one.
This also fixes #112 on Mac.
```
$ sudo installer -pkg amazon-corretto-8.202.08.2-macosx-x64.pkg -target / && java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
$ sudo installer -pkg amazon-corretto-8.212.04.2-macosx-x64.pkg -target / && java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed …
```

Use Corretto version as the value of the CFBundleVersion

---

src/common/autoconf/generated-configure.sh
src/common/autoconf/jdk-options.m4
src/hotspot/agent/src/share/classes/sun/jvm/hotspot/runtime/aarch64/AARCH64Frame.java

The original configuration set flag INCLUDE_SA as false when the CPU
arch is aarch64, causing `sa-jdi.jar` missing in the Corretto-8 build.
Without the jar, debug tools such `hsdb` and `clhsdb` are not able to
function correctly.
This is backported from JDK-8155627: https://bugs.openjdk.java.net/browse/JDK-8155627
```
amazon-corretto-8.212.04.2-linux-aarch64/lib/sa-jdi.jar
```

Backport JDK-8155627: Enable SA on AArch64

---

src/hotspot/src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/macroAssembler_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/macroAssembler_aarch64.hpp
src/hotspot/src/cpu/aarch64/vm/templateInterpreter_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/templateTable_aarch64.cpp
src/hotspot/src/share/vm/gc_implementation/g1/g1CodeCacheRemSet.cpp

update new atomic operations for ARM64
sync up with upstream ARM64 repo.
Works on OS: [e.g. …

update new atomic operations for ARM64

---

src/hotspot/src/cpu/x86/vm/x86_32.ad
src/hotspot/src/os_cpu/linux_x86/vm/os_linux_x86.cpp
src/hotspot/src/share/vm/classfile/defaultMethods.cpp
src/hotspot/src/share/vm/classfile/symbolTable.cpp
src/hotspot/src/share/vm/classfile/systemDictionary.cpp
src/hotspot/src/share/vm/memory/heapInspection.hpp
src/hotspot/src/share/vm/memory/metaspaceShared.hpp
src/hotspot/src/share/vm/oops/constantPool.hpp
src/hotspot/src/share/vm/prims/jvm.cpp
src/hotspot/src/share/vm/runtime/perfData.hpp
src/hotspot/src/share/vm/runtime/reflection.cpp
src/hotspot/src/share/vm/runtime/sharedRuntime.cpp
src/hotspot/src/share/vm/services/memTracker.hpp

Corretto-8 has enabled -Wreturn-warning. This patch allows
slowdebug build.
fix a bunch of places …

[backport] 8062808:Turn on the -Wreturn-type warning

---

src/hotspot/src/share/vm/prims/jni.cpp
src/hotspot/src/share/vm/utilities/hashFns.hpp
src/hotspot/src/share/vm/utilities/simpleOpenHashtable.cpp
src/hotspot/src/share/vm/utilities/simpleOpenHashtable.hpp

1. typo of default hash function
2. typo of HASH
3. compact after delete
4. add an unittest in +ExecuteInternalVMTests
Please fill in the following information …

Fix bugs in OpenHashtable

---

src/hotspot/src/cpu/aarch64/vm/c1_Runtime1_aarch64.cpp

we observe jcstress have some random failures on aarch64(a1.4x).  It's because c1 misses a …

[backport]8233839: aarch64: missing memory barrier in NewObjectArrayStub and NewTypeArrayStub

---

installers/linux/universal/deb/build.gradle

This commits add provides for both headful and headless runtime for Java 5 to 8.
This is to avoid installing another Java runtime during the groovy installation reported in #190.

corretto-8#190: Add provides for earlier jdks in debian

---

src/hotspot/src/cpu/aarch64/vm/macroAssembler_aarch64.cpp
src/hotspot/src/cpu/aarch64/vm/stubGenerator_aarch64.cpp
src/hotspot/src/share/vm/c1/c1_LIRGenerator.cpp

fix a bug for CMS on aarch64. 
C1 and template interpreter both miss a StoreStore membar between …

[backport] 8135018: AARCH64: Missing memory barriers for CMS collector

---

src/hotspot/src/share/vm/utilities/simpleOpenHashtable.hpp

This error is observed in macOS build with flag `--disable-precompiled-headers`.
Build tested on macOS w/ or w/o `--disable-precompiled-headers`.

Fix compilation error in simpleOpenHashtable when precompiled headers are disabled

---

CHANGELOG.md

macOS exclusive release (8.242.08.2) on March 10, 2020.
The following issues and enhancements are addressed in 8\.242\.08\.2
| Issue Name | Platform | Description | Link |
| --- | --- | --- | --- |
| Update macOS toolchain to meet Apple's notarization requirement |  macOS  | The minimum SDK requirement for notarization is SDK10\.9\. This change updates macOS toolchain from Macosx SDK10\.8 to SDK10\.10\. | [corretto-8#219](https://github.com/corretto/corretto-8/issues/219)

Update CHANGELOG.md to 8.242.08.2

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
installers/linux/universal/deb/build.gradle
installers/linux/universal/rpm/build.gradle
installers/linux/universal/tar/build.gradle
installers/mac/tar/build.gradle
installers/windows/zip/build.gradle

Add two properties to control build behavior:
* corretto.debug_level - Control the debug level of the build. Valid options including: release, fastdebug, debug, slowdebug.
* corretto.extra_config - Pass extra configuration flags to the build.
* On Linux
```
$ ./gradlew -Pcorretto.debug_level=slowdebug :installers:linux:universal:tar:build
...
A new configuration has been successfully created in
/corretto-8/installers/linux/universal/tar/corretto-build/buildRoot/src/build/linux-x86_64-normal-server-release
using configure arguments 'LIBCXX='-static-libstdc++ -static-libgcc' --with-update-version=252 --with-build-number=b09 --with-corretto-revision=2 --with-milestone=fcs --with-vendor-name='Amazon.com Inc.' --with-vendor-url=https://aws.amazon.com/corretto/ …
```

Support debug build and refactor common gradle logic

---

installers/windows/zip/build.gradle

Corretto 8 Linux and MacOS artifacts have `version.txt` which helps identifying Corretto full version. Add the missing `version.txt` file in Windows JDK and JRE images. 
Build Corretto 8 on Windows build environment and verify `version.txt` present in both JDK and JRE images.
Works on OS: Windows only

Add version.txt to Windows JDK and JRE

---

src/jdk/src/share/classes/java/nio/Bits.java
src/jdk/src/share/classes/sun/security/provider/ByteArrayAccess.java

This fixes an issue that happened during the import of the aarch64 port from Icedtea due to different implementation of JDK-8158260:
IcedTea: http://icedtea.classpath.org/hg/icedtea8-forest/jdk/rev/bc6eab2038c6
JDK: http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/rev/6021c95f5944
This led to IcedTea skipping 8186090, but Corretto, which uses the JDK implementation for 8158260, needs it.
**java.nio.Bits.unaligned() doesn't handle aarch64**
https://bugs.openjdk.java.net/browse/JDK-8186090
**PPC64: unaligned Unsafe.getInt can lead to the generation of illegal instructions**
https://bugs.openjdk.java.net/browse/JDK-8158260

Backport JDK-8186090: java.nio.Bits.unaligned() doesn't handle aarch64

---

CHANGELOG.md

CHANGELOG for Corretto release 8.262.10.2, the GA of Corretto 8 on Alpine Linux. Release date: Jul 14, 2020.

Update CHANGELOG.md for 8.262.10.2 (Alpine GA)

---

javafx/build.gradle

Upstream repos for OpenJFX were removed, build logic needs to be updated to point to 8u-dev to get the artifact.
Local build was able to download the correct artifact.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Update repo for JavaFX from 8u to 8u-dev

---

javafx/build.gradle

OpenJFX project has moved its development repository [jfx-dev/rt ](https://github.com/openjdk/jfx)to Github but the `8u-dev` repository was not included in the migration. We have noticed a couple transient errors when fetching OpenJFX8 source code from hg due to the repository reorganization or availability issue. Here we will allow passing OpenJFX8 source location as Gradle property for such the build won't be impacted by Hg availability.
Tested full Corretto8 generic Linux build with and without passing OpenJFX8 source `-PopenjdkPath` in Gradle. Both cases work.

Allow passing OpenJFX source location as Gradle property

---

installers/windows/README.md
installers/windows/zip/build.gradle

Reviewed-by: James Guo
Works on OS: [e.g. Amazon Linux 2 only]
Applies to version [e.g. "build …

Update windows build toolchain to vs2013

---

settings.gradle

Fixing build break on AArch64. Alpine project should not be included on aarch64 since it throws an exception when loading on this platform.

Update gradle logic to only include Alpine when not on AArch64

---

build.gradle

This value will get appended to the java version, not setting it will keep current behavior.
Example:
```
openjdk version "1.8.0_275-<milestone-name>"
OpenJDK Runtime Environment Corretto-8.275.01.1 (build 1.8.0_275-<milestone-name>)
OpenJDK 64-Bit Server VM Corretto-8.275.01.1 (build 25.275-b01, mixed mode)
```

Allow setting the milestone as corretto.milestone at build time

---

.github/ISSUE_TEMPLATE/bug_report.md
build.gradle

1. Replace the Oracle bug report URL of `http://bugreport.java.com/bugreport/crash.jsp` printed when VM crashes with Corretto issued URL.
```
#
#
#
#
#
#
Aborted
```
2. Update Github issue template for bug report.
- Build in local workspace
Works on OS: All platforms

Replace Oracle bug report URL by a Corretto URL when VM crashes

---

installers/linux/universal/rpm/scripts/postin_javac.sh.template

This change aligns with corretto-11 and onwards.
customer issue  #282
Works on OS: [e.g. Amazon …

create the symlink to jdk in /usr/lib/jvm
